#pragma once

#include <array>
#include <vector>

#include "ability.h"
#include "item.h"
#include "move.h"
#include "stat.h"
#include "type.h"

enum Who: uint8_t {
    Player,
    Opponent
};

enum Pokemon {
    Abomasnow,
    Abra,
    Absol,
    Aerodactyl,
    Aggron,
    Aipom,
    Alakazam,
    Altaria,
    Ambipom,
    Ampharos,
    Anorith,
    Arbok,
    Arcanine,
    Arceus,
    Ariados,
    Armaldo,
    Aron,
    Articuno,
    Azelf,
    Azumarill,
    Azurill,
    Bagon,
    Baltoy,
    Banette,
    Barboach,
    Bastiodon,
    Bayleef,
    Beautifly,
    Beedrill,
    Beldum,
    Bellossom,
    Bellsprout,
    Bibarel,
    Bidoof,
    Blastoise,
    Blaziken,
    Blissey,
    Bonsly,
    Breloom,
    Bronzong,
    Bronzor,
    Budew,
    Buizel,
    Bulbasaur,
    Buneary,
    Burmy,
    Butterfree,
    Cacnea,
    Cacturne,
    Camerupt,
    Carnivine,
    Carvanha,
    Cascoon,
    Castform,
    Caterpie,
    Celebi,
    Chansey,
    Charizard,
    Charmander,
    Charmeleon,
    Chatot,
    Cherrim,
    Cherubi,
    Chikorita,
    Chimchar,
    Chimecho,
    Chinchou,
    Chingling,
    Clamperl,
    Claydol,
    Clefable,
    Clefairy,
    Cleffa,
    Cloyster,
    Combee,
    Combusken,
    Corphish,
    Corsola,
    Cradily,
    Cranidos,
    Crawdaunt,
    Cresselia,
    Croagunk,
    Crobat,
    Croconaw,
    Cubone,
    Cyndaquil,
    Darkrai,
    Delcatty,
    Delibird,
    NormalDeoxys,
    AttackDeoxys,
    DefenseDeoxys,
    SpeedDeoxys,
    Dewgong,
    Dialga,
    Diglett,
    Ditto,
    Dodrio,
    Doduo,
    Donphan,
    Dragonair,
    Dragonite,
    Drapion,
    Dratini,
    Drifblim,
    Drifloon,
    Drowzee,
    Dugtrio,
    Dunsparce,
    Dusclops,
    Dusknoir,
    Duskull,
    Dustox,
    Eevee,
    Ekans,
    Electabuzz,
    Electivire,
    Electrike,
    Electrode,
    Elekid,
    Empoleon,
    Entei,
    Espeon,
    Exeggcute,
    Exeggutor,
    Exploud,
    Farfetchd,
    Fearow,
    Feebas,
    Feraligatr,
    Finneon,
    Flaaffy,
    Flareon,
    Floatzel,
    Flygon,
    Forretress,
    Froslass,
    Furret,
    Gabite,
    Gallade,
    Garchomp,
    Gardevoir,
    Gastly,
    Gastrodon,
    Gengar,
    Geodude,
    Gible,
    Girafarig,
    AlteredGiratina,
    OriginGiratina,
    Glaceon,
    Glalie,
    Glameow,
    Gligar,
    Gliscor,
    Gloom,
    Golbat,
    Goldeen,
    Golduck,
    Golem,
    Gorebyss,
    Granbull,
    Graveler,
    Grimer,
    Grotle,
    Groudon,
    Grovyle,
    Growlithe,
    Grumpig,
    Gulpin,
    Gyarados,
    Happiny,
    Hariyama,
    Haunter,
    Heatran,
    Heracross,
    Hippopotas,
    Hippowdon,
    Hitmonchan,
    Hitmonlee,
    Hitmontop,
    HoOh,
    Honchkrow,
    Hoothoot,
    Hoppip,
    Horsea,
    Houndoom,
    Houndour,
    Huntail,
    Hypno,
    Igglybuff,
    Illumise,
    Infernape,
    Ivysaur,
    Jigglypuff,
    Jirachi,
    Jolteon,
    Jumpluff,
    Jynx,
    Kabuto,
    Kabutops,
    Kadabra,
    Kakuna,
    Kangaskhan,
    Kecleon,
    Kingdra,
    Kingler,
    Kirlia,
    Koffing,
    Krabby,
    Kricketot,
    Kricketune,
    Kyogre,
    Lairon,
    Lanturn,
    Lapras,
    Larvitar,
    Latias,
    Latios,
    Leafeon,
    Ledian,
    Ledyba,
    Lickilicky,
    Lickitung,
    Lileep,
    Linoone,
    Lombre,
    Lopunny,
    Lotad,
    Loudred,
    Lucario,
    Ludicolo,
    Lugia,
    Lumineon,
    Lunatone,
    Luvdisc,
    Luxio,
    Luxray,
    Machamp,
    Machoke,
    Machop,
    Magby,
    Magcargo,
    Magikarp,
    Magmar,
    Magmortar,
    Magnemite,
    Magneton,
    Magnezone,
    Makuhita,
    Mamoswine,
    Manaphy,
    Manectric,
    Mankey,
    Mantine,
    Mantyke,
    Mareep,
    Marill,
    Marowak,
    Marshtomp,
    Masquerain,
    Mawile,
    Medicham,
    Meditite,
    Meganium,
    Meowth,
    Mesprit,
    Metagross,
    Metang,
    Metapod,
    Mew,
    Mewtwo,
    Mightyena,
    Milotic,
    Miltank,
    MimeJr,
    Minun,
    Misdreavus,
    Mismagius,
    Moltres,
    Monferno,
    Mothim,
    MrMime,
    Mudkip,
    Muk,
    Munchlax,
    Murkrow,
    Natu,
    Nidoking,
    Nidoqueen,
    NidoranF,
    NidoranM,
    Nidorina,
    Nidorino,
    Nincada,
    Ninetales,
    Ninjask,
    Noctowl,
    Nosepass,
    Numel,
    Nuzleaf,
    Octillery,
    Oddish,
    Omanyte,
    Omastar,
    Onix,
    Pachirisu,
    Palkia,
    Paras,
    Parasect,
    Pelipper,
    Persian,
    Phanpy,
    Phione,
    Pichu,
    Pidgeot,
    Pidgeotto,
    Pidgey,
    Pikachu,
    Piloswine,
    Pineco,
    Pinsir,
    Piplup,
    Plusle,
    Politoed,
    Poliwag,
    Poliwhirl,
    Poliwrath,
    Ponyta,
    Poochyena,
    Porygon,
    PorygonZ,
    Porygon2,
    Primeape,
    Prinplup,
    Probopass,
    Psyduck,
    Pupitar,
    Purugly,
    Quagsire,
    Quilava,
    Qwilfish,
    Raichu,
    Raikou,
    Ralts,
    Rampardos,
    Rapidash,
    Raticate,
    Rattata,
    Rayquaza,
    Regice,
    Regigigas,
    Regirock,
    Registeel,
    Relicanth,
    Remoraid,
    Rhydon,
    Rhyhorn,
    Rhyperior,
    Riolu,
    Roselia,
    Roserade,
    Rotom,
    HeatRotom,
    WashRotom,
    FrostRotom,
    FanRotom,
    MowRotom,
    Sableye,
    Salamence,
    Sandshrew,
    Sandslash,
    Sceptile,
    Scizor,
    Scyther,
    Seadra,
    Seaking,
    Sealeo,
    Seedot,
    Seel,
    Sentret,
    Seviper,
    Sharpedo,
    LandShaymin,
    SkyShaymin,
    Shedinja,
    Shelgon,
    Shellder,
    Shellos,
    Shieldon,
    Shiftry,
    Shinx,
    Shroomish,
    Shuckle,
    Shuppet,
    Silcoon,
    Skarmory,
    Skiploom,
    Skitty,
    Skorupi,
    Skuntank,
    Slaking,
    Slakoth,
    Slowbro,
    Slowking,
    Slowpoke,
    Slugma,
    Smeargle,
    Smoochum,
    Sneasel,
    Snorlax,
    Snorunt,
    Snover,
    Snubbull,
    Solrock,
    Spearow,
    Spheal,
    Spinarak,
    Spinda,
    Spiritomb,
    Spoink,
    Squirtle,
    Stantler,
    Staraptor,
    Staravia,
    Starly,
    Starmie,
    Staryu,
    Steelix,
    Stunky,
    Sudowoodo,
    Suicune,
    Sunflora,
    Sunkern,
    Surskit,
    Swablu,
    Swalot,
    Swampert,
    Swellow,
    Swinub,
    Taillow,
    Tangela,
    Tangrowth,
    Tauros,
    Teddiursa,
    Tentacool,
    Tentacruel,
    Togekiss,
    Togepi,
    Togetic,
    Torchic,
    Torkoal,
    Torterra,
    Totodile,
    Toxicroak,
    Trapinch,
    Treecko,
    Tropius,
    Turtwig,
    Typhlosion,
    Tyranitar,
    Tyrogue,
    Umbreon,
    Unown,
    Ursaring,
    Uxie,
    Vaporeon,
    Venomoth,
    Venonat,
    Venusaur,
    Vespiquen,
    Vibrava,
    Victreebel,
    Vigoroth,
    Vileplume,
    Volbeat,
    Voltorb,
    Vulpix,
    Wailmer,
    Wailord,
    Walrein,
    Wartortle,
    Weavile,
    Weedle,
    Weepinbell,
    Weezing,
    Whiscash,
    Whismur,
    Wigglytuff,
    Wingull,
    Wobbuffet,
    Wooper,
    WormadamP,
    WormadamS,
    WormadamT,
    Wurmple,
    Wynaut,
    Xatu,
    Yanma,
    Yanmega,
    Zangoose,
    Zapdos,
    Zigzagoon,
    Zubat,
    PokemonCount
};

inline const std::unordered_map<std::string, Pokemon> STRING_TO_POKEMON_MAP = {
    {"Abomasnow", Abomasnow},
    {"Abra", Abra},
    {"Absol", Absol},
    {"Aerodactyl", Aerodactyl},
    {"Aggron", Aggron},
    {"Aipom", Aipom},
    {"Alakazam", Alakazam},
    {"Altaria", Altaria},
    {"Ambipom", Ambipom},
    {"Ampharos", Ampharos},
    {"Anorith", Anorith},
    {"Arbok", Arbok},
    {"Arcanine", Arcanine},
    {"Arceus", Arceus},
    {"Ariados", Ariados},
    {"Armaldo", Armaldo},
    {"Aron", Aron},
    {"Articuno", Articuno},
    {"Azelf", Azelf},
    {"Azumarill", Azumarill},
    {"Azurill", Azurill},
    {"Bagon", Bagon},
    {"Baltoy", Baltoy},
    {"Banette", Banette},
    {"Barboach", Barboach},
    {"Bastiodon", Bastiodon},
    {"Bayleef", Bayleef},
    {"Beautifly", Beautifly},
    {"Beedrill", Beedrill},
    {"Beldum", Beldum},
    {"Bellossom", Bellossom},
    {"Bellsprout", Bellsprout},
    {"Bibarel", Bibarel},
    {"Bidoof", Bidoof},
    {"Blastoise", Blastoise},
    {"Blaziken", Blaziken},
    {"Blissey", Blissey},
    {"Bonsly", Bonsly},
    {"Breloom", Breloom},
    {"Bronzong", Bronzong},
    {"Bronzor", Bronzor},
    {"Budew", Budew},
    {"Buizel", Buizel},
    {"Bulbasaur", Bulbasaur},
    {"Buneary", Buneary},
    {"Burmy", Burmy},
    {"Butterfree", Butterfree},
    {"Cacnea", Cacnea},
    {"Cacturne", Cacturne},
    {"Camerupt", Camerupt},
    {"Carnivine", Carnivine},
    {"Carvanha", Carvanha},
    {"Cascoon", Cascoon},
    {"Castform", Castform},
    {"Caterpie", Caterpie},
    {"Celebi", Celebi},
    {"Chansey", Chansey},
    {"Charizard", Charizard},
    {"Charmander", Charmander},
    {"Charmeleon", Charmeleon},
    {"Chatot", Chatot},
    {"Cherrim", Cherrim},
    {"Cherubi", Cherubi},
    {"Chikorita", Chikorita},
    {"Chimchar", Chimchar},
    {"Chimecho", Chimecho},
    {"Chinchou", Chinchou},
    {"Chingling", Chingling},
    {"Clamperl", Clamperl},
    {"Claydol", Claydol},
    {"Clefable", Clefable},
    {"Clefairy", Clefairy},
    {"Cleffa", Cleffa},
    {"Cloyster", Cloyster},
    {"Combee", Combee},
    {"Combusken", Combusken},
    {"Corphish", Corphish},
    {"Corsola", Corsola},
    {"Cradily", Cradily},
    {"Cranidos", Cranidos},
    {"Crawdaunt", Crawdaunt},
    {"Cresselia", Cresselia},
    {"Croagunk", Croagunk},
    {"Crobat", Crobat},
    {"Croconaw", Croconaw},
    {"Cubone", Cubone},
    {"Cyndaquil", Cyndaquil},
    {"Darkrai", Darkrai},
    {"Delcatty", Delcatty},
    {"Delibird", Delibird},
    {"NormalDeoxys", NormalDeoxys},
    {"AttackDeoxys", AttackDeoxys},
    {"DefenseDeoxys", DefenseDeoxys},
    {"SpeedDeoxys", SpeedDeoxys},
    {"Dewgong", Dewgong},
    {"Dialga", Dialga},
    {"Diglett", Diglett},
    {"Ditto", Ditto},
    {"Dodrio", Dodrio},
    {"Doduo", Doduo},
    {"Donphan", Donphan},
    {"Dragonair", Dragonair},
    {"Dragonite", Dragonite},
    {"Drapion", Drapion},
    {"Dratini", Dratini},
    {"Drifblim", Drifblim},
    {"Drifloon", Drifloon},
    {"Drowzee", Drowzee},
    {"Dugtrio", Dugtrio},
    {"Dunsparce", Dunsparce},
    {"Dusclops", Dusclops},
    {"Dusknoir", Dusknoir},
    {"Duskull", Duskull},
    {"Dustox", Dustox},
    {"Eevee", Eevee},
    {"Ekans", Ekans},
    {"Electabuzz", Electabuzz},
    {"Electivire", Electivire},
    {"Electrike", Electrike},
    {"Electrode", Electrode},
    {"Elekid", Elekid},
    {"Empoleon", Empoleon},
    {"Entei", Entei},
    {"Espeon", Espeon},
    {"Exeggcute", Exeggcute},
    {"Exeggutor", Exeggutor},
    {"Exploud", Exploud},
    {"Farfetch'd", Farfetchd},
    {"Fearow", Fearow},
    {"Feebas", Feebas},
    {"Feraligatr", Feraligatr},
    {"Finneon", Finneon},
    {"Flaaffy", Flaaffy},
    {"Flareon", Flareon},
    {"Floatzel", Floatzel},
    {"Flygon", Flygon},
    {"Forretress", Forretress},
    {"Froslass", Froslass},
    {"Furret", Furret},
    {"Gabite", Gabite},
    {"Gallade", Gallade},
    {"Garchomp", Garchomp},
    {"Gardevoir", Gardevoir},
    {"Gastly", Gastly},
    {"Gastrodon", Gastrodon},
    {"Gengar", Gengar},
    {"Geodude", Geodude},
    {"Gible", Gible},
    {"Girafarig", Girafarig},
    {"AlteredGiratina", AlteredGiratina},
    {"OriginGiratina", OriginGiratina},
    {"Glaceon", Glaceon},
    {"Glalie", Glalie},
    {"Glameow", Glameow},
    {"Gligar", Gligar},
    {"Gliscor", Gliscor},
    {"Gloom", Gloom},
    {"Golbat", Golbat},
    {"Goldeen", Goldeen},
    {"Golduck", Golduck},
    {"Golem", Golem},
    {"Gorebyss", Gorebyss},
    {"Granbull", Granbull},
    {"Graveler", Graveler},
    {"Grimer", Grimer},
    {"Grotle", Grotle},
    {"Groudon", Groudon},
    {"Grovyle", Grovyle},
    {"Growlithe", Growlithe},
    {"Grumpig", Grumpig},
    {"Gulpin", Gulpin},
    {"Gyarados", Gyarados},
    {"Happiny", Happiny},
    {"Hariyama", Hariyama},
    {"Haunter", Haunter},
    {"Heatran", Heatran},
    {"Heracross", Heracross},
    {"Hippopotas", Hippopotas},
    {"Hippowdon", Hippowdon},
    {"Hitmonchan", Hitmonchan},
    {"Hitmonlee", Hitmonlee},
    {"Hitmontop", Hitmontop},
    {"Ho-oh", HoOh},
    {"Honchkrow", Honchkrow},
    {"Hoothoot", Hoothoot},
    {"Hoppip", Hoppip},
    {"Horsea", Horsea},
    {"Houndoom", Houndoom},
    {"Houndour", Houndour},
    {"Huntail", Huntail},
    {"Hypno", Hypno},
    {"Igglybuff", Igglybuff},
    {"Illumise", Illumise},
    {"Infernape", Infernape},
    {"Ivysaur", Ivysaur},
    {"Jigglypuff", Jigglypuff},
    {"Jirachi", Jirachi},
    {"Jolteon", Jolteon},
    {"Jumpluff", Jumpluff},
    {"Jynx", Jynx},
    {"Kabuto", Kabuto},
    {"Kabutops", Kabutops},
    {"Kadabra", Kadabra},
    {"Kakuna", Kakuna},
    {"Kangaskhan", Kangaskhan},
    {"Kecleon", Kecleon},
    {"Kingdra", Kingdra},
    {"Kingler", Kingler},
    {"Kirlia", Kirlia},
    {"Koffing", Koffing},
    {"Krabby", Krabby},
    {"Kricketot", Kricketot},
    {"Kricketune", Kricketune},
    {"Kyogre", Kyogre},
    {"Lairon", Lairon},
    {"Lanturn", Lanturn},
    {"Lapras", Lapras},
    {"Larvitar", Larvitar},
    {"Latias", Latias},
    {"Latios", Latios},
    {"Leafeon", Leafeon},
    {"Ledian", Ledian},
    {"Ledyba", Ledyba},
    {"Lickilicky", Lickilicky},
    {"Lickitung", Lickitung},
    {"Lileep", Lileep},
    {"Linoone", Linoone},
    {"Lombre", Lombre},
    {"Lopunny", Lopunny},
    {"Lotad", Lotad},
    {"Loudred", Loudred},
    {"Lucario", Lucario},
    {"Ludicolo", Ludicolo},
    {"Lugia", Lugia},
    {"Lumineon", Lumineon},
    {"Lunatone", Lunatone},
    {"Luvdisc", Luvdisc},
    {"Luxio", Luxio},
    {"Luxray", Luxray},
    {"Machamp", Machamp},
    {"Machoke", Machoke},
    {"Machop", Machop},
    {"Magby", Magby},
    {"Magcargo", Magcargo},
    {"Magikarp", Magikarp},
    {"Magmar", Magmar},
    {"Magmortar", Magmortar},
    {"Magnemite", Magnemite},
    {"Magneton", Magneton},
    {"Magnezone", Magnezone},
    {"Makuhita", Makuhita},
    {"Mamoswine", Mamoswine},
    {"Manaphy", Manaphy},
    {"Manectric", Manectric},
    {"Mankey", Mankey},
    {"Mantine", Mantine},
    {"Mantyke", Mantyke},
    {"Mareep", Mareep},
    {"Marill", Marill},
    {"Marowak", Marowak},
    {"Marshtomp", Marshtomp},
    {"Masquerain", Masquerain},
    {"Mawile", Mawile},
    {"Medicham", Medicham},
    {"Meditite", Meditite},
    {"Meganium", Meganium},
    {"Meowth", Meowth},
    {"Mesprit", Mesprit},
    {"Metagross", Metagross},
    {"Metang", Metang},
    {"Metapod", Metapod},
    {"Mew", Mew},
    {"Mewtwo", Mewtwo},
    {"Mightyena", Mightyena},
    {"Milotic", Milotic},
    {"Miltank", Miltank},
    {"Mime Jr.", MimeJr},
    {"Minun", Minun},
    {"Misdreavus", Misdreavus},
    {"Mismagius", Mismagius},
    {"Moltres", Moltres},
    {"Monferno", Monferno},
    {"Mothim", Mothim},
    {"Mr. Mime", MrMime},
    {"Mudkip", Mudkip},
    {"Muk", Muk},
    {"Munchlax", Munchlax},
    {"Murkrow", Murkrow},
    {"Natu", Natu},
    {"Nidoking", Nidoking},
    {"Nidoqueen", Nidoqueen},
    {"Nidoran(F)", NidoranF},
    {"Nidoran(M)", NidoranM},
    {"Nidorina", Nidorina},
    {"Nidorino", Nidorino},
    {"Nincada", Nincada},
    {"Ninetales", Ninetales},
    {"Ninjask", Ninjask},
    {"Noctowl", Noctowl},
    {"Nosepass", Nosepass},
    {"Numel", Numel},
    {"Nuzleaf", Nuzleaf},
    {"Octillery", Octillery},
    {"Oddish", Oddish},
    {"Omanyte", Omanyte},
    {"Omastar", Omastar},
    {"Onix", Onix},
    {"Pachirisu", Pachirisu},
    {"Palkia", Palkia},
    {"Paras", Paras},
    {"Parasect", Parasect},
    {"Pelipper", Pelipper},
    {"Persian", Persian},
    {"Phanpy", Phanpy},
    {"Phione", Phione},
    {"Pichu", Pichu},
    {"Pidgeot", Pidgeot},
    {"Pidgeotto", Pidgeotto},
    {"Pidgey", Pidgey},
    {"Pikachu", Pikachu},
    {"Piloswine", Piloswine},
    {"Pineco", Pineco},
    {"Pinsir", Pinsir},
    {"Piplup", Piplup},
    {"Plusle", Plusle},
    {"Politoed", Politoed},
    {"Poliwag", Poliwag},
    {"Poliwhirl", Poliwhirl},
    {"Poliwrath", Poliwrath},
    {"Ponyta", Ponyta},
    {"Poochyena", Poochyena},
    {"Porygon", Porygon},
    {"Porygon-Z", PorygonZ},
    {"Porygon2", Porygon2},
    {"Primeape", Primeape},
    {"Prinplup", Prinplup},
    {"Probopass", Probopass},
    {"Psyduck", Psyduck},
    {"Pupitar", Pupitar},
    {"Purugly", Purugly},
    {"Quagsire", Quagsire},
    {"Quilava", Quilava},
    {"Qwilfish", Qwilfish},
    {"Raichu", Raichu},
    {"Raikou", Raikou},
    {"Ralts", Ralts},
    {"Rampardos", Rampardos},
    {"Rapidash", Rapidash},
    {"Raticate", Raticate},
    {"Rattata", Rattata},
    {"Rayquaza", Rayquaza},
    {"Regice", Regice},
    {"Regigigas", Regigigas},
    {"Regirock", Regirock},
    {"Registeel", Registeel},
    {"Relicanth", Relicanth},
    {"Remoraid", Remoraid},
    {"Rhydon", Rhydon},
    {"Rhyhorn", Rhyhorn},
    {"Rhyperior", Rhyperior},
    {"Riolu", Riolu},
    {"Roselia", Roselia},
    {"Roserade", Roserade},
    {"Rotom", Rotom},
    {"HeatRotom", HeatRotom},
    {"WashRotom", WashRotom},
    {"FrostRotom", FrostRotom},
    {"FanRotom", FanRotom},
    {"MowRotom", MowRotom},
    {"Sableye", Sableye},
    {"Salamence", Salamence},
    {"Sandshrew", Sandshrew},
    {"Sandslash", Sandslash},
    {"Sceptile", Sceptile},
    {"Scizor", Scizor},
    {"Scyther", Scyther},
    {"Seadra", Seadra},
    {"Seaking", Seaking},
    {"Sealeo", Sealeo},
    {"Seedot", Seedot},
    {"Seel", Seel},
    {"Sentret", Sentret},
    {"Seviper", Seviper},
    {"Sharpedo", Sharpedo},
    {"SkyShaymin", SkyShaymin},
    {"LandShaymin", LandShaymin},
    {"Shedinja", Shedinja},
    {"Shelgon", Shelgon},
    {"Shellder", Shellder},
    {"Shellos", Shellos},
    {"Shieldon", Shieldon},
    {"Shiftry", Shiftry},
    {"Shinx", Shinx},
    {"Shroomish", Shroomish},
    {"Shuckle", Shuckle},
    {"Shuppet", Shuppet},
    {"Silcoon", Silcoon},
    {"Skarmory", Skarmory},
    {"Skiploom", Skiploom},
    {"Skitty", Skitty},
    {"Skorupi", Skorupi},
    {"Skuntank", Skuntank},
    {"Slaking", Slaking},
    {"Slakoth", Slakoth},
    {"Slowbro", Slowbro},
    {"Slowking", Slowking},
    {"Slowpoke", Slowpoke},
    {"Slugma", Slugma},
    {"Smeargle", Smeargle},
    {"Smoochum", Smoochum},
    {"Sneasel", Sneasel},
    {"Snorlax", Snorlax},
    {"Snorunt", Snorunt},
    {"Snover", Snover},
    {"Snubbull", Snubbull},
    {"Solrock", Solrock},
    {"Spearow", Spearow},
    {"Spheal", Spheal},
    {"Spinarak", Spinarak},
    {"Spinda", Spinda},
    {"Spiritomb", Spiritomb},
    {"Spoink", Spoink},
    {"Squirtle", Squirtle},
    {"Stantler", Stantler},
    {"Staraptor", Staraptor},
    {"Staravia", Staravia},
    {"Starly", Starly},
    {"Starmie", Starmie},
    {"Staryu", Staryu},
    {"Steelix", Steelix},
    {"Stunky", Stunky},
    {"Sudowoodo", Sudowoodo},
    {"Suicune", Suicune},
    {"Sunflora", Sunflora},
    {"Sunkern", Sunkern},
    {"Surskit", Surskit},
    {"Swablu", Swablu},
    {"Swalot", Swalot},
    {"Swampert", Swampert},
    {"Swellow", Swellow},
    {"Swinub", Swinub},
    {"Taillow", Taillow},
    {"Tangela", Tangela},
    {"Tangrowth", Tangrowth},
    {"Tauros", Tauros},
    {"Teddiursa", Teddiursa},
    {"Tentacool", Tentacool},
    {"Tentacruel", Tentacruel},
    {"Togekiss", Togekiss},
    {"Togepi", Togepi},
    {"Togetic", Togetic},
    {"Torchic", Torchic},
    {"Torkoal", Torkoal},
    {"Torterra", Torterra},
    {"Totodile", Totodile},
    {"Toxicroak", Toxicroak},
    {"Trapinch", Trapinch},
    {"Treecko", Treecko},
    {"Tropius", Tropius},
    {"Turtwig", Turtwig},
    {"Typhlosion", Typhlosion},
    {"Tyranitar", Tyranitar},
    {"Tyrogue", Tyrogue},
    {"Umbreon", Umbreon},
    {"Unown", Unown},
    {"Ursaring", Ursaring},
    {"Uxie", Uxie},
    {"Vaporeon", Vaporeon},
    {"Venomoth", Venomoth},
    {"Venonat", Venonat},
    {"Venusaur", Venusaur},
    {"Vespiquen", Vespiquen},
    {"Vibrava", Vibrava},
    {"Victreebel", Victreebel},
    {"Vigoroth", Vigoroth},
    {"Vileplume", Vileplume},
    {"Volbeat", Volbeat},
    {"Voltorb", Voltorb},
    {"Vulpix", Vulpix},
    {"Wailmer", Wailmer},
    {"Wailord", Wailord},
    {"Walrein", Walrein},
    {"Wartortle", Wartortle},
    {"Weavile", Weavile},
    {"Weedle", Weedle},
    {"Weepinbell", Weepinbell},
    {"Weezing", Weezing},
    {"Whiscash", Whiscash},
    {"Whismur", Whismur},
    {"Wigglytuff", Wigglytuff},
    {"Wingull", Wingull},
    {"Wobbuffet", Wobbuffet},
    {"Wooper", Wooper},
    {"WormadamP", WormadamP},
    {"WormadamS", WormadamS},
    {"WormadamT", WormadamT},
    {"Wurmple", Wurmple},
    {"Wynaut", Wynaut},
    {"Xatu", Xatu},
    {"Yanma", Yanma},
    {"Yanmega", Yanmega},
    {"Zangoose", Zangoose},
    {"Zapdos", Zapdos},
    {"Zigzagoon", Zigzagoon},
    {"Zubat", Zubat},
};

inline const std::unordered_map<Pokemon, std::vector<Ability>>
POKEMON_TO_ABILITY_MAP = {
    {Abomasnow, {SnowWarning}},
    {Abra, {InnerFocus, Synchronize}},
    {Absol, {Pressure, SuperLuck}},
    {Aerodactyl, {Pressure, RockHead}},
    {Aggron, {RockHead, Sturdy}},
    {Aipom, {Pickup, RunAway}},
    {Alakazam, {InnerFocus, Synchronize}},
    {Altaria, {NaturalCure}},
    {Ambipom, {Pickup, Technician}},
    {Ampharos, {Static}},
    {Anorith, {BattleArmor}},
    {Arbok, {Intimidate, ShedSkin}},
    {Arcanine, {FlashFire, Intimidate}},
    {Arceus, {Multitype}},
    {Ariados, {Insomnia, Swarm}},
    {Armaldo, {BattleArmor}},
    {Aron, {RockHead, Sturdy}},
    {Articuno, {Pressure}},
    {Azelf, {Levitate}},
    {Azumarill, {HugePower, ThickFat}},
    {Azurill, {HugePower, ThickFat}},
    {Bagon, {RockHead}},
    {Baltoy, {Levitate}},
    {Banette, {Frisk, Insomnia}},
    {Barboach, {Anticipation, Oblivious}},
    {Bastiodon, {Sturdy}},
    {Bayleef, {Overgrow}},
    {Beautifly, {Swarm}},
    {Beedrill, {Swarm}},
    {Beldum, {ClearBody}},
    {Bellossom, {Chlorophyll}},
    {Bellsprout, {Chlorophyll}},
    {Bibarel, {Simple, Unaware}},
    {Bidoof, {Simple, Unaware}},
    {Blastoise, {Torrent}},
    {Blaziken, {Blaze}},
    {Blissey, {NaturalCure, SereneGrace}},
    {Bonsly, {RockHead, Sturdy}},
    {Breloom, {EffectSpore, PoisonHeal}},
    {Bronzong, {Heatproof, Levitate}},
    {Bronzor, {Heatproof, Levitate}},
    {Budew, {NaturalCure, PoisonPoint}},
    {Buizel, {SwiftSwim}},
    {Bulbasaur, {Overgrow}},
    {Buneary, {Klutz, RunAway}},
    {Burmy, {ShedSkin}},
    {Butterfree, {Compoundeyes}},
    {Cacnea, {SandVeil}},
    {Cacturne, {SandVeil}},
    {Camerupt, {MagmaArmor, SolidRock}},
    {Carnivine, {Levitate}},
    {Carvanha, {RoughSkin}},
    {Cascoon, {ShedSkin}},
    {Castform, {Forecast}},
    {Caterpie, {ShieldDust}},
    {Celebi, {NaturalCure}},
    {Chansey, {NaturalCure, SereneGrace}},
    {Charizard, {Blaze}},
    {Charmander, {Blaze}},
    {Charmeleon, {Blaze}},
    {Chatot, {KeenEye, TangledFeet}},
    {Cherrim, {FlowerGift}},
    {Cherubi, {Chlorophyll}},
    {Chikorita, {Overgrow}},
    {Chimchar, {Blaze}},
    {Chimecho, {Levitate}},
    {Chinchou, {Illuminate, VoltAbsorb}},
    {Chingling, {Levitate}},
    {Clamperl, {ShellArmor}},
    {Claydol, {Levitate}},
    {Clefable, {CuteCharm, MagicGuard}},
    {Clefairy, {CuteCharm, MagicGuard}},
    {Cleffa, {CuteCharm, MagicGuard}},
    {Cloyster, {ShellArmor, SkillLink}},
    {Combee, {HoneyGather}},
    {Combusken, {Blaze}},
    {Corphish, {HyperCutter, ShellArmor}},
    {Corsola, {Hustle, NaturalCure}},
    {Cradily, {SuctionCups}},
    {Cranidos, {MoldBreaker}},
    {Crawdaunt, {HyperCutter, ShellArmor}},
    {Cresselia, {Levitate}},
    {Croagunk, {Anticipation, DrySkin}},
    {Crobat, {InnerFocus}},
    {Croconaw, {Torrent}},
    {Cubone, {LightningRod, RockHead}},
    {Cyndaquil, {Blaze}},
    {Darkrai, {BadDreams}},
    {Delcatty, {CuteCharm, Normalize}},
    {Delibird, {Hustle, VitalSpirit}},
    {NormalDeoxys, {Pressure}},
    {AttackDeoxys, {Pressure}},
    {DefenseDeoxys, {Pressure}},
    {SpeedDeoxys, {Pressure}},
    {Dewgong, {Hydration, ThickFat}},
    {Dialga, {Pressure}},
    {Diglett, {ArenaTrap, SandVeil}},
    {Ditto, {Limber}},
    {Dodrio, {EarlyBird, RunAway}},
    {Doduo, {EarlyBird, RunAway}},
    {Donphan, {Sturdy}},
    {Dragonair, {ShedSkin}},
    {Dragonite, {InnerFocus}},
    {Drapion, {BattleArmor, Sniper}},
    {Dratini, {ShedSkin}},
    {Drifblim, {Aftermath, Unburden}},
    {Drifloon, {Aftermath, Unburden}},
    {Drowzee, {Forewarn, Insomnia}},
    {Dugtrio, {ArenaTrap, SandVeil}},
    {Dunsparce, {RunAway, SereneGrace}},
    {Dusclops, {Pressure}},
    {Dusknoir, {Pressure}},
    {Duskull, {Levitate}},
    {Dustox, {ShieldDust}},
    {Eevee, {Adaptability, RunAway}},
    {Ekans, {Intimidate, ShedSkin}},
    {Electabuzz, {Static}},
    {Electivire, {MotorDrive}},
    {Electrike, {LightningRod, Static}},
    {Electrode, {Soundproof, Static}},
    {Elekid, {Static}},
    {Empoleon, {Torrent}},
    {Entei, {Pressure}},
    {Espeon, {Synchronize}},
    {Exeggcute, {Chlorophyll}},
    {Exeggutor, {Chlorophyll}},
    {Exploud, {Soundproof}},
    {Farfetchd, {InnerFocus, KeenEye}},
    {Fearow, {KeenEye}},
    {Feebas, {SwiftSwim}},
    {Feraligatr, {Torrent}},
    {Finneon, {StormDrain, SwiftSwim}},
    {Flaaffy, {Static}},
    {Flareon, {FlashFire}},
    {Floatzel, {SwiftSwim}},
    {Flygon, {Levitate}},
    {Forretress, {Sturdy}},
    {Froslass, {SnowCloak}},
    {Furret, {KeenEye, RunAway}},
    {Gabite, {SandVeil}},
    {Gallade, {Steadfast}},
    {Garchomp, {SandVeil}},
    {Gardevoir, {Synchronize, Trace}},
    {Gastly, {Levitate}},
    {Gastrodon, {StickyHold, StormDrain}},
    {Gengar, {Levitate}},
    {Geodude, {RockHead, Sturdy}},
    {Gible, {SandVeil}},
    {Girafarig, {EarlyBird, InnerFocus}},
    {AlteredGiratina, {Pressure}},
    {OriginGiratina, {Levitate}},
    {Glaceon, {SnowCloak}},
    {Glalie, {IceBody, InnerFocus}},
    {Glameow, {Limber, OwnTempo}},
    {Gligar, {HyperCutter, SandVeil}},
    {Gliscor, {HyperCutter, SandVeil}},
    {Gloom, {Chlorophyll}},
    {Golbat, {InnerFocus}},
    {Goldeen, {SwiftSwim, WaterVeil}},
    {Golduck, {CloudNine, Damp}},
    {Golem, {RockHead, Sturdy}},
    {Gorebyss, {SwiftSwim}},
    {Granbull, {Intimidate, QuickFeet}},
    {Graveler, {RockHead, Sturdy}},
    {Grimer, {Stench, StickyHold}},
    {Grotle, {Overgrow}},
    {Groudon, {Drought}},
    {Grovyle, {Overgrow}},
    {Growlithe, {FlashFire, Intimidate}},
    {Grumpig, {OwnTempo, ThickFat}},
    {Gulpin, {LiquidOoze, StickyHold}},
    {Gyarados, {Intimidate}},
    {Happiny, {NaturalCure, SereneGrace}},
    {Hariyama, {Guts, ThickFat}},
    {Haunter, {Levitate}},
    {Heatran, {FlashFire}},
    {Heracross, {Guts, Swarm}},
    {Hippopotas, {SandStream}},
    {Hippowdon, {SandStream}},
    {Hitmonchan, {IronFist, KeenEye}},
    {Hitmonlee, {Limber, Reckless}},
    {Hitmontop, {Intimidate, Technician}},
    {HoOh, {Pressure}},
    {Honchkrow, {Insomnia, SuperLuck}},
    {Hoothoot, {Insomnia, KeenEye}},
    {Hoppip, {Chlorophyll, LeafGuard}},
    {Horsea, {Sniper, SwiftSwim}},
    {Houndoom, {EarlyBird, FlashFire}},
    {Houndour, {EarlyBird, FlashFire}},
    {Huntail, {SwiftSwim}},
    {Hypno, {Forewarn, Insomnia}},
    {Igglybuff, {CuteCharm}},
    {Illumise, {Oblivious, TintedLens}},
    {Infernape, {Blaze}},
    {Ivysaur, {Overgrow}},
    {Jigglypuff, {CuteCharm}},
    {Jirachi, {SereneGrace}},
    {Jolteon, {VoltAbsorb}},
    {Jumpluff, {Chlorophyll, LeafGuard}},
    {Jynx, {Forewarn, Oblivious}},
    {Kabuto, {BattleArmor, SwiftSwim}},
    {Kabutops, {BattleArmor, SwiftSwim}},
    {Kadabra, {InnerFocus, Synchronize}},
    {Kakuna, {ShedSkin}},
    {Kangaskhan, {EarlyBird, Scrappy}},
    {Kecleon, {ColorChange}},
    {Kingdra, {Sniper, SwiftSwim}},
    {Kingler, {HyperCutter, ShellArmor}},
    {Kirlia, {Synchronize, Trace}},
    {Koffing, {Levitate}},
    {Krabby, {HyperCutter, ShellArmor}},
    {Kricketot, {ShedSkin}},
    {Kricketune, {Swarm}},
    {Kyogre, {Drizzle}},
    {Lairon, {RockHead, Sturdy}},
    {Lanturn, {Illuminate, VoltAbsorb}},
    {Lapras, {ShellArmor, WaterAbsorb}},
    {Larvitar, {Guts}},
    {Latias, {Levitate}},
    {Latios, {Levitate}},
    {Leafeon, {LeafGuard}},
    {Ledian, {EarlyBird, Swarm}},
    {Ledyba, {EarlyBird, Swarm}},
    {Lickilicky, {Oblivious, OwnTempo}},
    {Lickitung, {Oblivious, OwnTempo}},
    {Lileep, {SuctionCups}},
    {Linoone, {Gluttony, Pickup}},
    {Lombre, {RainDish, SwiftSwim}},
    {Lopunny, {CuteCharm, Klutz}},
    {Lotad, {RainDish, SwiftSwim}},
    {Loudred, {Soundproof}},
    {Lucario, {InnerFocus, Steadfast}},
    {Ludicolo, {RainDish, SwiftSwim}},
    {Lugia, {Pressure}},
    {Lumineon, {StormDrain, SwiftSwim}},
    {Lunatone, {Levitate}},
    {Luvdisc, {SwiftSwim}},
    {Luxio, {Intimidate, Rivalry}},
    {Luxray, {Intimidate, Rivalry}},
    {Machamp, {Guts, NoGuard}},
    {Machoke, {Guts, NoGuard}},
    {Machop, {Guts, NoGuard}},
    {Magby, {FlameBody}},
    {Magcargo, {FlameBody, MagmaArmor}},
    {Magikarp, {SwiftSwim}},
    {Magmar, {FlameBody}},
    {Magmortar, {FlameBody}},
    {Magnemite, {MagnetPull, Sturdy}},
    {Magneton, {MagnetPull, Sturdy}},
    {Magnezone, {MagnetPull, Sturdy}},
    {Makuhita, {Guts, ThickFat}},
    {Mamoswine, {Oblivious, SnowCloak}},
    {Manaphy, {Hydration}},
    {Manectric, {LightningRod, Static}},
    {Mankey, {AngerPoint, VitalSpirit}},
    {Mantine, {SwiftSwim, WaterAbsorb}},
    {Mantyke, {SwiftSwim, WaterAbsorb}},
    {Mareep, {Static}},
    {Marill, {HugePower, ThickFat}},
    {Marowak, {LightningRod, RockHead}},
    {Marshtomp, {Torrent}},
    {Masquerain, {Intimidate}},
    {Mawile, {HyperCutter, Intimidate}},
    {Medicham, {PurePower}},
    {Meditite, {PurePower}},
    {Meganium, {Overgrow}},
    {Meowth, {Pickup, Technician}},
    {Mesprit, {Levitate}},
    {Metagross, {ClearBody}},
    {Metang, {ClearBody}},
    {Metapod, {ShedSkin}},
    {Mew, {Synchronize}},
    {Mewtwo, {Pressure}},
    {Mightyena, {Intimidate, QuickFeet}},
    {Milotic, {MarvelScale}},
    {Miltank, {Scrappy, ThickFat}},
    {MimeJr, {Filter, Soundproof}},
    {Minun, {Minus}},
    {Misdreavus, {Levitate}},
    {Mismagius, {Levitate}},
    {Moltres, {Pressure}},
    {Monferno, {Blaze}},
    {Mothim, {Swarm}},
    {MrMime, {Filter, Soundproof}},
    {Mudkip, {Torrent}},
    {Muk, {Stench, StickyHold}},
    {Munchlax, {Pickup, ThickFat}},
    {Murkrow, {Insomnia, SuperLuck}},
    {Natu, {EarlyBird, Synchronize}},
    {Nidoking, {PoisonPoint, Rivalry}},
    {Nidoqueen, {PoisonPoint, Rivalry}},
    {NidoranF, {PoisonPoint, Rivalry}},
    {NidoranM, {PoisonPoint, Rivalry}},
    {Nidorina, {PoisonPoint, Rivalry}},
    {Nidorino, {PoisonPoint, Rivalry}},
    {Nincada, {Compoundeyes}},
    {Ninetales, {FlashFire}},
    {Ninjask, {SpeedBoost}},
    {Noctowl, {Insomnia, KeenEye}},
    {Nosepass, {MagnetPull, Sturdy}},
    {Numel, {Oblivious, Simple}},
    {Nuzleaf, {Chlorophyll, EarlyBird}},
    {Octillery, {Sniper, SuctionCups}},
    {Oddish, {Chlorophyll}},
    {Omanyte, {ShellArmor, SwiftSwim}},
    {Omastar, {ShellArmor, SwiftSwim}},
    {Onix, {RockHead, Sturdy}},
    {Pachirisu, {Pickup, RunAway}},
    {Palkia, {Pressure}},
    {Paras, {DrySkin, EffectSpore}},
    {Parasect, {DrySkin, EffectSpore}},
    {Pelipper, {KeenEye}},
    {Persian, {Limber, Technician}},
    {Phanpy, {Pickup}},
    {Phione, {Hydration}},
    {Pichu, {Static}},
    {Pidgeot, {KeenEye, TangledFeet}},
    {Pidgeotto, {KeenEye, TangledFeet}},
    {Pidgey, {KeenEye, TangledFeet}},
    {Pikachu, {Static}},
    {Piloswine, {Oblivious, SnowCloak}},
    {Pineco, {Sturdy}},
    {Pinsir, {HyperCutter, MoldBreaker}},
    {Piplup, {Torrent}},
    {Plusle, {Plus}},
    {Politoed, {Damp, WaterAbsorb}},
    {Poliwag, {Damp, WaterAbsorb}},
    {Poliwhirl, {Damp, WaterAbsorb}},
    {Poliwrath, {Damp, WaterAbsorb}},
    {Ponyta, {FlashFire, RunAway}},
    {Poochyena, {QuickFeet, RunAway}},
    {Porygon, {Download, Trace}},
    {PorygonZ, {Adaptability, Download}},
    {Porygon2, {Download, Trace}},
    {Primeape, {AngerPoint, VitalSpirit}},
    {Prinplup, {Torrent}},
    {Probopass, {MagnetPull, Sturdy}},
    {Psyduck, {CloudNine, Damp}},
    {Pupitar, {ShedSkin}},
    {Purugly, {OwnTempo, ThickFat}},
    {Quagsire, {Damp, WaterAbsorb}},
    {Quilava, {Blaze}},
    {Qwilfish, {PoisonPoint, SwiftSwim}},
    {Raichu, {Static}},
    {Raikou, {Pressure}},
    {Ralts, {Synchronize, Trace}},
    {Rampardos, {MoldBreaker}},
    {Rapidash, {FlashFire, RunAway}},
    {Raticate, {Guts, RunAway}},
    {Rattata, {Guts, RunAway}},
    {Rayquaza, {AirLock}},
    {Regice, {ClearBody}},
    {Regigigas, {SlowStart}},
    {Regirock, {ClearBody}},
    {Registeel, {ClearBody}},
    {Relicanth, {RockHead, SwiftSwim}},
    {Remoraid, {Hustle, Sniper}},
    {Rhydon, {LightningRod, RockHead}},
    {Rhyhorn, {LightningRod, RockHead}},
    {Rhyperior, {LightningRod, SolidRock}},
    {Riolu, {InnerFocus, Steadfast}},
    {Roselia, {NaturalCure, PoisonPoint}},
    {Roserade, {NaturalCure, PoisonPoint}},
    {Rotom, {Levitate}},
    {Sableye, {KeenEye, Stall}},
    {Salamence, {Intimidate}},
    {Sandshrew, {SandVeil}},
    {Sandslash, {SandVeil}},
    {Sceptile, {Overgrow}},
    {Scizor, {Swarm, Technician}},
    {Scyther, {Swarm, Technician}},
    {Seadra, {PoisonPoint, Sniper}},
    {Seaking, {SwiftSwim, WaterVeil}},
    {Sealeo, {IceBody, ThickFat}},
    {Seedot, {Chlorophyll, EarlyBird}},
    {Seel, {Hydration, ThickFat}},
    {Sentret, {KeenEye, RunAway}},
    {Seviper, {ShedSkin}},
    {Sharpedo, {RoughSkin}},
    {LandShaymin, {NaturalCure}},
    {SkyShaymin, {SereneGrace}},
    {Shedinja, {WonderGuard}},
    {Shelgon, {RockHead}},
    {Shellder, {ShellArmor, SkillLink}},
    {Shellos, {StickyHold, StormDrain}},
    {Shieldon, {Sturdy}},
    {Shiftry, {Chlorophyll, EarlyBird}},
    {Shinx, {Intimidate, Rivalry}},
    {Shroomish, {EffectSpore, PoisonHeal}},
    {Shuckle, {Gluttony, Sturdy}},
    {Shuppet, {Frisk, Insomnia}},
    {Silcoon, {ShedSkin}},
    {Skarmory, {KeenEye, Sturdy}},
    {Skiploom, {Chlorophyll, LeafGuard}},
    {Skitty, {CuteCharm, Normalize}},
    {Skorupi, {BattleArmor, Sniper}},
    {Skuntank, {Aftermath, Stench}},
    {Slaking, {Truant}},
    {Slakoth, {Truant}},
    {Slowbro, {Oblivious, OwnTempo}},
    {Slowking, {Oblivious, OwnTempo}},
    {Slowpoke, {Oblivious, OwnTempo}},
    {Slugma, {FlameBody, MagmaArmor}},
    {Smeargle, {OwnTempo, Technician}},
    {Smoochum, {Forewarn, Oblivious}},
    {Sneasel, {InnerFocus, KeenEye}},
    {Snorlax, {Immunity, ThickFat}},
    {Snorunt, {IceBody, InnerFocus}},
    {Snover, {SnowWarning}},
    {Snubbull, {Intimidate, RunAway}},
    {Solrock, {Levitate}},
    {Spearow, {KeenEye}},
    {Spheal, {IceBody, ThickFat}},
    {Spinarak, {Insomnia, Swarm}},
    {Spinda, {OwnTempo, TangledFeet}},
    {Spiritomb, {Pressure}},
    {Spoink, {OwnTempo, ThickFat}},
    {Squirtle, {Torrent}},
    {Stantler, {Frisk, Intimidate}},
    {Staraptor, {Intimidate}},
    {Staravia, {Intimidate}},
    {Starly, {KeenEye}},
    {Starmie, {Illuminate, NaturalCure}},
    {Staryu, {Illuminate, NaturalCure}},
    {Steelix, {RockHead, Sturdy}},
    {Stunky, {Aftermath, Stench}},
    {Sudowoodo, {RockHead, Sturdy}},
    {Suicune, {Pressure}},
    {Sunflora, {Chlorophyll, SolarPower}},
    {Sunkern, {Chlorophyll, SolarPower}},
    {Surskit, {SwiftSwim}},
    {Swablu, {NaturalCure}},
    {Swalot, {LiquidOoze, StickyHold}},
    {Swampert, {Torrent}},
    {Swellow, {Guts}},
    {Swinub, {Oblivious, SnowCloak}},
    {Taillow, {Guts}},
    {Tangela, {Chlorophyll, LeafGuard}},
    {Tangrowth, {Chlorophyll, LeafGuard}},
    {Tauros, {AngerPoint, Intimidate}},
    {Teddiursa, {Pickup, QuickFeet}},
    {Tentacool, {ClearBody, LiquidOoze}},
    {Tentacruel, {ClearBody, LiquidOoze}},
    {Togekiss, {Hustle, SereneGrace}},
    {Togepi, {Hustle, SereneGrace}},
    {Togetic, {Hustle, SereneGrace}},
    {Torchic, {Blaze}},
    {Torkoal, {WhiteSmoke}},
    {Torterra, {Overgrow}},
    {Totodile, {Torrent}},
    {Toxicroak, {Anticipation, DrySkin}},
    {Trapinch, {ArenaTrap, HyperCutter}},
    {Treecko, {Overgrow}},
    {Tropius, {Chlorophyll, SolarPower}},
    {Turtwig, {Overgrow}},
    {Typhlosion, {Blaze}},
    {Tyranitar, {SandStream}},
    {Tyrogue, {Guts, Steadfast}},
    {Umbreon, {Synchronize}},
    {Unown, {Levitate}},
    {Ursaring, {Guts, QuickFeet}},
    {Uxie, {Levitate}},
    {Vaporeon, {WaterAbsorb}},
    {Venomoth, {ShieldDust, TintedLens}},
    {Venonat, {Compoundeyes, TintedLens}},
    {Venusaur, {Overgrow}},
    {Vespiquen, {Pressure}},
    {Vibrava, {Levitate}},
    {Victreebel, {Chlorophyll}},
    {Vigoroth, {VitalSpirit}},
    {Vileplume, {Chlorophyll}},
    {Volbeat, {Illuminate, Swarm}},
    {Voltorb, {Soundproof, Static}},
    {Vulpix, {FlashFire}},
    {Wailmer, {Oblivious, WaterVeil}},
    {Wailord, {Oblivious, WaterVeil}},
    {Walrein, {IceBody, ThickFat}},
    {Wartortle, {Torrent}},
    {Weavile, {Pressure}},
    {Weedle, {ShieldDust}},
    {Weepinbell, {Chlorophyll}},
    {Weezing, {Levitate}},
    {Whiscash, {Anticipation, Oblivious}},
    {Whismur, {Soundproof}},
    {Wigglytuff, {CuteCharm}},
    {Wingull, {KeenEye}},
    {Wobbuffet, {ShadowTag}},
    {Wooper, {Damp, WaterAbsorb}},
    {WormadamP, {Anticipation}},
    {WormadamS, {Anticipation}},
    {WormadamT, {Anticipation}},
    {Wurmple, {ShieldDust}},
    {Wynaut, {ShadowTag}},
    {Xatu, {EarlyBird, Synchronize}},
    {Yanma, {Compoundeyes, SpeedBoost}},
    {Yanmega, {SpeedBoost, TintedLens}},
    {Zangoose, {Immunity}},
    {Zapdos, {Pressure}},
    {Zigzagoon, {Gluttony, Pickup}},
    {Zubat, {InnerFocus}},
};

struct CustomPokemon {
    Pokemon name;
    Ability ability;
    uint8_t level;
    Item item;
    std::array<PokemonType, 2> types;
    std::vector<Move> moves;
    std::array<uint16_t,NoStat> stats;
    double pounds;

    uint16_t get_stat(const Stat stat) const {
        return stats[stat];
    }

};
